title:              Il Regno della Sintassi
email:              hiemsword08+rsintassi@pm.me
description:        Benvenuto nel Regno della Sintassi! Qui puoi vedere i miei blog sintassiosi
author:             Re della Sintassi
baseurl:            ""
url:                "regnodellasintassi.surge.sh"
timezone: Europe/Rome
version: '2.8.9'

permalink: /:categories/:title/


# Social Profiles
twitter_username:   RSintassi
github_username:    
facebook_username:  
instagram_username:  redellasintassi
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
#paginate:           5
#paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: posts


# The URL for the staticman API bridge endpoint
staticman_url: https://regnosintassi-staticman.herokuapp.com/v2/entry/HiemSword/regnodellasintassi-site/master/comments
