name: Jekyll site CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Jekyll
      uses: jerryjvl/jekyll-build-action@v1
      
    - run: cd ./_site
      
    - name: Check dir
      run: ls -l
      
    - name: Deploy to regnodellasintassi.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'regnodellasintassi.surge.sh'
        project: './_site'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}


    - name: Upload Jekyll build
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./_site # or path/to/artifact
